# Generated by Django 4.2 on 2023-04-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_alter_photography_photo'),
        ('accounts', '0002_account_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='galery.photography', verbose_name='Избранные'),
        ),
    ]
